package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsCoupon;
import com.dzmsoft.sms.base.pojo.SmsCouponExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsCouponMapper {
    public PageList<SmsCoupon> selectByExample(SmsCouponExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int countByExample(SmsCouponExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int deleteByExample(SmsCouponExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int insert(SmsCoupon record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int insertSelective(SmsCoupon record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    List<SmsCoupon> selectByExample(SmsCouponExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    SmsCoupon selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsCoupon record,
            @Param("example") SmsCouponExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByExample(@Param("record") SmsCoupon record,
            @Param("example") SmsCouponExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByPrimaryKeySelective(SmsCoupon record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_coupon
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByPrimaryKey(SmsCoupon record);
}