package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.dto.SmsCommodityOrderDto;
import com.dzmsoft.sms.base.pojo.SmsCommodityOrder;
import com.dzmsoft.sms.base.pojo.SmsCommodityOrderExample;
import com.dzmsoft.sms.base.pojo.udf.SmsCommodityOrderUdfExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsCommodityOrderMapper {
    public PageList<SmsCommodityOrder> selectByExample(SmsCommodityOrderExample example,PageBounds pageBounds);
    
    List<SmsCommodityOrderDto> selectWithCommodity(SmsCommodityOrderUdfExample example);
    
    PageList<SmsCommodityOrderDto> selectWithCommodity(SmsCommodityOrderUdfExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int countByExample(SmsCommodityOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int deleteByExample(SmsCommodityOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int insert(SmsCommodityOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int insertSelective(SmsCommodityOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    List<SmsCommodityOrder> selectByExample(SmsCommodityOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    SmsCommodityOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsCommodityOrder record, @Param("example") SmsCommodityOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int updateByExample(@Param("record") SmsCommodityOrder record, @Param("example") SmsCommodityOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int updateByPrimaryKeySelective(SmsCommodityOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_commodity_order
     *
     * @mbggenerated Sun May 29 08:54:46 CST 2016
     */
    int updateByPrimaryKey(SmsCommodityOrder record);
}