package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsEmployeeShift;
import com.dzmsoft.sms.base.pojo.SmsEmployeeShiftExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsEmployeeShiftMapper {
    public PageList<SmsEmployeeShift> selectByExample(SmsEmployeeShiftExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int countByExample(SmsEmployeeShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int deleteByExample(SmsEmployeeShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int insert(SmsEmployeeShift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int insertSelective(SmsEmployeeShift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    List<SmsEmployeeShift> selectByExample(SmsEmployeeShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    SmsEmployeeShift selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsEmployeeShift record, @Param("example") SmsEmployeeShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int updateByExample(@Param("record") SmsEmployeeShift record, @Param("example") SmsEmployeeShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int updateByPrimaryKeySelective(SmsEmployeeShift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_shift
     *
     * @mbggenerated Tue Jul 19 21:25:27 CST 2016
     */
    int updateByPrimaryKey(SmsEmployeeShift record);
}