package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsEmployeeTeam;
import com.dzmsoft.sms.base.pojo.SmsEmployeeTeamExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsEmployeeTeamMapper {
    public PageList<SmsEmployeeTeam> selectByExample(SmsEmployeeTeamExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsEmployeeTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsEmployeeTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsEmployeeTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsEmployeeTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsEmployeeTeam> selectByExample(SmsEmployeeTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsEmployeeTeam selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsEmployeeTeam record, @Param("example") SmsEmployeeTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsEmployeeTeam record, @Param("example") SmsEmployeeTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsEmployeeTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_employee_team
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsEmployeeTeam record);
}