package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsHouseholdPriceRule;
import com.dzmsoft.sms.base.pojo.SmsHouseholdPriceRuleExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsHouseholdPriceRuleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int countByExample(SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int deleteByExample(SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int insert(SmsHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int insertSelective(SmsHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    List<SmsHouseholdPriceRule> selectByExampleWithBLOBs(SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    List<SmsHouseholdPriceRule> selectByExample(SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    SmsHouseholdPriceRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsHouseholdPriceRule record,
            @Param("example") SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SmsHouseholdPriceRule record,
            @Param("example") SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int updateByExample(@Param("record") SmsHouseholdPriceRule record,
            @Param("example") SmsHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int updateByPrimaryKeySelective(SmsHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SmsHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_price_rule
     * @mbggenerated  Tue Jun 21 22:34:11 CST 2016
     */
    int updateByPrimaryKey(SmsHouseholdPriceRule record);

    public PageList<SmsHouseholdPriceRule> selectByExample(SmsHouseholdPriceRuleExample example,PageBounds pageBounds);
}