package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsHouseholdRequire;
import com.dzmsoft.sms.base.pojo.SmsHouseholdRequireExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsHouseholdRequireMapper {
    public PageList<SmsHouseholdRequire> selectByExample(SmsHouseholdRequireExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsHouseholdRequireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsHouseholdRequireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsHouseholdRequire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsHouseholdRequire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsHouseholdRequire> selectByExample(SmsHouseholdRequireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsHouseholdRequire selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsHouseholdRequire record, @Param("example") SmsHouseholdRequireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsHouseholdRequire record, @Param("example") SmsHouseholdRequireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsHouseholdRequire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_require
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsHouseholdRequire record);
}