package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsHouseBuilding;
import com.dzmsoft.sms.base.pojo.SmsHouseBuildingExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsHouseBuildingMapper {
    public PageList<SmsHouseBuilding> selectByExample(SmsHouseBuildingExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int countByExample(SmsHouseBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int deleteByExample(SmsHouseBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int insert(SmsHouseBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int insertSelective(SmsHouseBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    List<SmsHouseBuilding> selectByExample(SmsHouseBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    SmsHouseBuilding selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsHouseBuilding record, @Param("example") SmsHouseBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int updateByExample(@Param("record") SmsHouseBuilding record, @Param("example") SmsHouseBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int updateByPrimaryKeySelective(SmsHouseBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_house_building
     *
     * @mbggenerated Thu Jul 07 18:50:23 CST 2016
     */
    int updateByPrimaryKey(SmsHouseBuilding record);
}