package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsHousing;
import com.dzmsoft.sms.base.pojo.SmsHousingExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsHousingMapper {
    
    String selectTopIndex(SmsHousingExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int countByExample(SmsHousingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int deleteByExample(SmsHousingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int insert(SmsHousing record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int insertSelective(SmsHousing record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    List<SmsHousing> selectByExample(SmsHousingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    SmsHousing selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsHousing record,
            @Param("example") SmsHousingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int updateByExample(@Param("record") SmsHousing record,
            @Param("example") SmsHousingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int updateByPrimaryKeySelective(SmsHousing record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_housing
     * @mbggenerated  Tue Aug 16 22:34:44 CST 2016
     */
    int updateByPrimaryKey(SmsHousing record);

    public PageList<SmsHousing> selectByExample(SmsHousingExample example,PageBounds pageBounds);
}