package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsHouseholdBag;
import com.dzmsoft.sms.base.pojo.SmsHouseholdBagExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsHouseholdBagMapper {
    public PageList<SmsHouseholdBag> selectByExample(SmsHouseholdBagExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsHouseholdBagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsHouseholdBagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsHouseholdBag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsHouseholdBag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsHouseholdBag> selectByExample(SmsHouseholdBagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsHouseholdBag selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsHouseholdBag record, @Param("example") SmsHouseholdBagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsHouseholdBag record, @Param("example") SmsHouseholdBagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsHouseholdBag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_household_bag
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsHouseholdBag record);
}