package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.dto.SmsHouseholdOrderDto;
import com.dzmsoft.sms.base.pojo.SmsHouseholdOrder;
import com.dzmsoft.sms.base.pojo.SmsHouseholdOrderExample;
import com.dzmsoft.sms.base.pojo.udf.SmsHouseholdOrderUdfExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsHouseholdOrderMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsHouseholdOrderExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsHouseholdOrderExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsHouseholdOrder record);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsHouseholdOrder record);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsHouseholdOrder> selectByExample(SmsHouseholdOrderExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    SmsHouseholdOrder selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsHouseholdOrder record,
            @Param("example") SmsHouseholdOrderExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsHouseholdOrder record,
            @Param("example") SmsHouseholdOrderExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsHouseholdOrder record);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_household_order
     * @mbggenerated  Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsHouseholdOrder record);
    public PageList<SmsHouseholdOrderDto> selectByUdfExample(SmsHouseholdOrderUdfExample example,PageBounds pageBounds);
    public PageList<SmsHouseholdOrder> selectByExample(SmsHouseholdOrderExample example,PageBounds pageBounds);
}