package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsMemberAddress;
import com.dzmsoft.sms.base.pojo.SmsMemberAddressExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsMemberAddressMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int countByExample(SmsMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int deleteByExample(SmsMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int insert(SmsMemberAddress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int insertSelective(SmsMemberAddress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    List<SmsMemberAddress> selectByExample(SmsMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    SmsMemberAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMemberAddress record,
            @Param("example") SmsMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int updateByExample(@Param("record") SmsMemberAddress record,
            @Param("example") SmsMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMemberAddress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_member_address
     * @mbggenerated  Sat Aug 13 19:27:37 CST 2016
     */
    int updateByPrimaryKey(SmsMemberAddress record);

    public PageList<SmsMemberAddress> selectByExample(SmsMemberAddressExample example,PageBounds pageBounds);
}