package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsMemberCard;
import com.dzmsoft.sms.base.pojo.SmsMemberCardExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsMemberCardMapper {
    public PageList<SmsMemberCard> selectByExample(SmsMemberCardExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsMemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsMemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsMemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsMemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsMemberCard> selectByExample(SmsMemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsMemberCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMemberCard record, @Param("example") SmsMemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsMemberCard record, @Param("example") SmsMemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsMemberCard record);
}