package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsMemberCardConsume;
import com.dzmsoft.sms.base.pojo.SmsMemberCardConsumeExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsMemberCardConsumeMapper {
    public PageList<SmsMemberCardConsume> selectByExample(SmsMemberCardConsumeExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsMemberCardConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsMemberCardConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsMemberCardConsume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsMemberCardConsume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsMemberCardConsume> selectByExample(SmsMemberCardConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsMemberCardConsume selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMemberCardConsume record, @Param("example") SmsMemberCardConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsMemberCardConsume record, @Param("example") SmsMemberCardConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMemberCardConsume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_card_consume
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsMemberCardConsume record);
}