package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsMemberCoupon;
import com.dzmsoft.sms.base.pojo.SmsMemberCouponExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsMemberCouponMapper {
    public PageList<SmsMemberCoupon> selectByExample(SmsMemberCouponExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsMemberCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsMemberCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsMemberCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsMemberCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsMemberCoupon> selectByExample(SmsMemberCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsMemberCoupon selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMemberCoupon record, @Param("example") SmsMemberCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsMemberCoupon record, @Param("example") SmsMemberCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMemberCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_coupon
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsMemberCoupon record);
}