package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsMallCommodity;
import com.dzmsoft.sms.base.pojo.SmsMallCommodityExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsMallCommodityMapper {
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int countByExample(SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int deleteByExample(SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int insert(SmsMallCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int insertSelective(SmsMallCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    List<SmsMallCommodity> selectByExampleWithBLOBs(SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    List<SmsMallCommodity> selectByExample(SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    SmsMallCommodity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMallCommodity record,
            @Param("example") SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SmsMallCommodity record,
            @Param("example") SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int updateByExample(@Param("record") SmsMallCommodity record,
            @Param("example") SmsMallCommodityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMallCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SmsMallCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_commodity
     * @mbggenerated  Fri Jul 01 09:58:31 CST 2016
     */
    int updateByPrimaryKey(SmsMallCommodity record);

    String selectTopIndex(SmsMallCommodityExample example);
    
    public PageList<SmsMallCommodity> selectByExample(SmsMallCommodityExample example,PageBounds pageBounds);
}