package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsMallBrand;
import com.dzmsoft.sms.base.pojo.SmsMallBrandExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsMallBrandMapper {
    
    String selectTopIndex(SmsMallBrandExample example);
    
    public PageList<SmsMallBrand> selectByExample(SmsMallBrandExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int countByExample(SmsMallBrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int deleteByExample(SmsMallBrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int insert(SmsMallBrand record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int insertSelective(SmsMallBrand record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    List<SmsMallBrand> selectByExample(SmsMallBrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    SmsMallBrand selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMallBrand record,
            @Param("example") SmsMallBrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByExample(@Param("record") SmsMallBrand record,
            @Param("example") SmsMallBrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMallBrand record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_mall_brand
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByPrimaryKey(SmsMallBrand record);
}