package com.dzmsoft.sms.base.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dzmsoft.sms.base.dto.SmsNewhomeOrderDto;
import com.dzmsoft.sms.base.pojo.SmsNewhomeOrder;
import com.dzmsoft.sms.base.pojo.SmsNewhomeOrderExample;
import com.dzmsoft.sms.base.pojo.udf.SmsNewhomeOrderUdfExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface SmsNewhomeOrderMapper {
    public PageList<SmsNewhomeOrderDto> selectByUdfExample(SmsNewhomeOrderUdfExample example,PageBounds pageBounds);
    
    public PageList<SmsNewhomeOrder> selectByExample(SmsNewhomeOrderExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int countByExample(SmsNewhomeOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int deleteByExample(SmsNewhomeOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int insert(SmsNewhomeOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int insertSelective(SmsNewhomeOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    List<SmsNewhomeOrder> selectByExample(SmsNewhomeOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    SmsNewhomeOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsNewhomeOrder record,
            @Param("example") SmsNewhomeOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByExample(@Param("record") SmsNewhomeOrder record,
            @Param("example") SmsNewhomeOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByPrimaryKeySelective(SmsNewhomeOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_newhome_order
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    int updateByPrimaryKey(SmsNewhomeOrder record);
}