package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsNewhomePriceRule;
import com.dzmsoft.sms.base.pojo.SmsNewhomePriceRuleExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsNewhomePriceRuleMapper {
    public PageList<SmsNewhomePriceRule> selectByExample(SmsNewhomePriceRuleExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int countByExample(SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int deleteByExample(SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int insert(SmsNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int insertSelective(SmsNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    List<SmsNewhomePriceRule> selectByExampleWithBLOBs(SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    List<SmsNewhomePriceRule> selectByExample(SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    SmsNewhomePriceRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsNewhomePriceRule record, @Param("example") SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SmsNewhomePriceRule record, @Param("example") SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int updateByExample(@Param("record") SmsNewhomePriceRule record, @Param("example") SmsNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int updateByPrimaryKeySelective(SmsNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SmsNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_newhome_price_rule
     *
     * @mbggenerated Wed Jun 22 16:11:38 CST 2016
     */
    int updateByPrimaryKey(SmsNewhomePriceRule record);
}