package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsOrder;
import com.dzmsoft.sms.base.pojo.SmsOrderExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsOrderMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int countByExample(SmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int deleteByExample(SmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int insert(SmsOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int insertSelective(SmsOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    List<SmsOrder> selectByExample(SmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    SmsOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsOrder record,
            @Param("example") SmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int updateByExample(@Param("record") SmsOrder record, @Param("example") SmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int updateByPrimaryKeySelective(SmsOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_order
     * @mbggenerated  Sat Aug 13 18:57:25 CST 2016
     */
    int updateByPrimaryKey(SmsOrder record);

    public PageList<SmsOrder> selectByExample(SmsOrderExample example,PageBounds pageBounds);
}