package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsPersonRequire;
import com.dzmsoft.sms.base.pojo.SmsPersonRequireExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsPersonRequireMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int countByExample(SmsPersonRequireExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int deleteByExample(SmsPersonRequireExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int insert(SmsPersonRequire record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int insertSelective(SmsPersonRequire record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    List<SmsPersonRequire> selectByExample(SmsPersonRequireExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    SmsPersonRequire selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsPersonRequire record,
            @Param("example") SmsPersonRequireExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int updateByExample(@Param("record") SmsPersonRequire record,
            @Param("example") SmsPersonRequireExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int updateByPrimaryKeySelective(SmsPersonRequire record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require
     * @mbggenerated  Tue Jun 21 14:39:18 CST 2016
     */
    int updateByPrimaryKey(SmsPersonRequire record);

    public PageList<SmsPersonRequire> selectByExample(SmsPersonRequireExample example,PageBounds pageBounds);
}