package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsPersonRequireLine;
import com.dzmsoft.sms.base.pojo.SmsPersonRequireLineExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsPersonRequireLineMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int countByExample(SmsPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int deleteByExample(SmsPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int insert(SmsPersonRequireLine record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int insertSelective(SmsPersonRequireLine record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    List<SmsPersonRequireLine> selectByExample(SmsPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    SmsPersonRequireLine selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsPersonRequireLine record,
            @Param("example") SmsPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int updateByExample(@Param("record") SmsPersonRequireLine record,
            @Param("example") SmsPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int updateByPrimaryKeySelective(SmsPersonRequireLine record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_person_require_line
     * @mbggenerated  Mon Jun 13 13:04:36 CST 2016
     */
    int updateByPrimaryKey(SmsPersonRequireLine record);

    public PageList<SmsPersonRequireLine> selectByExample(SmsPersonRequireLineExample example,PageBounds pageBounds);
}