package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsRegion;
import com.dzmsoft.sms.base.pojo.SmsRegionExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsRegionMapper {
    public PageList<SmsRegion> selectByExample(SmsRegionExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int countByExample(SmsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByExample(SmsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insert(SmsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int insertSelective(SmsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    List<SmsRegion> selectByExample(SmsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    SmsRegion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsRegion record, @Param("example") SmsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByExample(@Param("record") SmsRegion record, @Param("example") SmsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKeySelective(SmsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_region
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    int updateByPrimaryKey(SmsRegion record);
}