package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsServiceEmployee;
import com.dzmsoft.sms.base.pojo.SmsServiceEmployeeExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsServiceEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int countByExample(SmsServiceEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int deleteByExample(SmsServiceEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int insert(SmsServiceEmployee record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int insertSelective(SmsServiceEmployee record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    List<SmsServiceEmployee> selectByExample(SmsServiceEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    SmsServiceEmployee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsServiceEmployee record,
            @Param("example") SmsServiceEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int updateByExample(@Param("record") SmsServiceEmployee record,
            @Param("example") SmsServiceEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int updateByPrimaryKeySelective(SmsServiceEmployee record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_service_employee
     * @mbggenerated  Mon Jul 04 17:45:37 CST 2016
     */
    int updateByPrimaryKey(SmsServiceEmployee record);

    public PageList<SmsServiceEmployee> selectByExample(SmsServiceEmployeeExample example,PageBounds pageBounds);
}