package com.dzmsoft.sms.base.dao;

import com.dzmsoft.sms.base.pojo.SmsShift;
import com.dzmsoft.sms.base.pojo.SmsShiftExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SmsShiftMapper {
    public PageList<SmsShift> selectByExample(SmsShiftExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int countByExample(SmsShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int deleteByExample(SmsShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int insert(SmsShift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int insertSelective(SmsShift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    List<SmsShift> selectByExample(SmsShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    SmsShift selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsShift record, @Param("example") SmsShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int updateByExample(@Param("record") SmsShift record, @Param("example") SmsShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int updateByPrimaryKeySelective(SmsShift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_shift
     *
     * @mbggenerated Sat May 14 22:23:58 CST 2016
     */
    int updateByPrimaryKey(SmsShift record);
}