package com.dzmsoft.sms.base.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class SmsCoupon {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.id
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.face_value
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private BigDecimal faceValue;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.effective_date
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private Date effectiveDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.expiration_date
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private Date expirationDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.creator
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private String creator;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.create_time
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.supplier
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private String supplier;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.description
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sms_coupon.status
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.id
     * @return  the value of sms_coupon.id
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.id
     * @param id  the value for sms_coupon.id
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.face_value
     * @return  the value of sms_coupon.face_value
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public BigDecimal getFaceValue() {
        return faceValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.face_value
     * @param faceValue  the value for sms_coupon.face_value
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setFaceValue(BigDecimal faceValue) {
        this.faceValue = faceValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.effective_date
     * @return  the value of sms_coupon.effective_date
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.effective_date
     * @param effectiveDate  the value for sms_coupon.effective_date
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.expiration_date
     * @return  the value of sms_coupon.expiration_date
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.expiration_date
     * @param expirationDate  the value for sms_coupon.expiration_date
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.creator
     * @return  the value of sms_coupon.creator
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.creator
     * @param creator  the value for sms_coupon.creator
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.create_time
     * @return  the value of sms_coupon.create_time
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.create_time
     * @param createTime  the value for sms_coupon.create_time
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.supplier
     * @return  the value of sms_coupon.supplier
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.supplier
     * @param supplier  the value for sms_coupon.supplier
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.description
     * @return  the value of sms_coupon.description
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.description
     * @param description  the value for sms_coupon.description
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sms_coupon.status
     * @return  the value of sms_coupon.status
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sms_coupon.status
     * @param status  the value for sms_coupon.status
     * @mbggenerated  Wed May 04 17:07:43 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}