package com.dzmsoft.sms.base.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Iterator;

public class SmsEmployeeScheduleExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public SmsEmployeeScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2,
                String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(
                    condition,
                    new java.sql.Date(value1.getTime()),
                    new java.sql.Date(value2.getTime()),
                    property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmployeeIsNull() {
            addCriterion("employee is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIsNotNull() {
            addCriterion("employee is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEqualTo(String value) {
            addCriterion("employee =", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeNotEqualTo(String value) {
            addCriterion("employee <>", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeGreaterThan(String value) {
            addCriterion("employee >", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeGreaterThanOrEqualTo(String value) {
            addCriterion("employee >=", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeLessThan(String value) {
            addCriterion("employee <", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeLessThanOrEqualTo(String value) {
            addCriterion("employee <=", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeLike(String value) {
            addCriterion("employee like", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeNotLike(String value) {
            addCriterion("employee not like", value, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeIn(List<String> values) {
            addCriterion("employee in", values, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeNotIn(List<String> values) {
            addCriterion("employee not in", values, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeBetween(String value1, String value2) {
            addCriterion("employee between", value1, value2, "employee");
            return (Criteria) this;
        }

        public Criteria andEmployeeNotBetween(String value1, String value2) {
            addCriterion("employee not between", value1, value2, "employee");
            return (Criteria) this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return (Criteria) this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return (Criteria) this;
        }

        public Criteria andDayEqualTo(Date value) {
            addCriterionForJDBCDate("day =", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotEqualTo(Date value) {
            addCriterionForJDBCDate("day <>", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThan(Date value) {
            addCriterionForJDBCDate("day >", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("day >=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThan(Date value) {
            addCriterionForJDBCDate("day <", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("day <=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayIn(List<Date> values) {
            addCriterionForJDBCDate("day in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotIn(List<Date> values) {
            addCriterionForJDBCDate("day not in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("day between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("day not between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("supplier is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("supplier is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("supplier =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("supplier <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("supplier >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("supplier >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("supplier <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("supplier <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("supplier like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("supplier not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("supplier in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("supplier not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("supplier between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("supplier not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("updator is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("updator is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("updator =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("updator <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("updator >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("updator >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("updator <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("updator <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("updator like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("updator not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("updator in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("updator not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("updator between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("updator not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andShiftIsNull() {
            addCriterion("shift is null");
            return (Criteria) this;
        }

        public Criteria andShiftIsNotNull() {
            addCriterion("shift is not null");
            return (Criteria) this;
        }

        public Criteria andShiftEqualTo(String value) {
            addCriterion("shift =", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftNotEqualTo(String value) {
            addCriterion("shift <>", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftGreaterThan(String value) {
            addCriterion("shift >", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftGreaterThanOrEqualTo(String value) {
            addCriterion("shift >=", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftLessThan(String value) {
            addCriterion("shift <", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftLessThanOrEqualTo(String value) {
            addCriterion("shift <=", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftLike(String value) {
            addCriterion("shift like", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftNotLike(String value) {
            addCriterion("shift not like", value, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftIn(List<String> values) {
            addCriterion("shift in", values, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftNotIn(List<String> values) {
            addCriterion("shift not in", values, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftBetween(String value1, String value2) {
            addCriterion("shift between", value1, value2, "shift");
            return (Criteria) this;
        }

        public Criteria andShiftNotBetween(String value1, String value2) {
            addCriterion("shift not between", value1, value2, "shift");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSixIsNull() {
            addCriterion("six is null");
            return (Criteria) this;
        }

        public Criteria andSixIsNotNull() {
            addCriterion("six is not null");
            return (Criteria) this;
        }

        public Criteria andSixEqualTo(String value) {
            addCriterion("six =", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixNotEqualTo(String value) {
            addCriterion("six <>", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixGreaterThan(String value) {
            addCriterion("six >", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixGreaterThanOrEqualTo(String value) {
            addCriterion("six >=", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixLessThan(String value) {
            addCriterion("six <", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixLessThanOrEqualTo(String value) {
            addCriterion("six <=", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixLike(String value) {
            addCriterion("six like", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixNotLike(String value) {
            addCriterion("six not like", value, "six");
            return (Criteria) this;
        }

        public Criteria andSixIn(List<String> values) {
            addCriterion("six in", values, "six");
            return (Criteria) this;
        }

        public Criteria andSixNotIn(List<String> values) {
            addCriterion("six not in", values, "six");
            return (Criteria) this;
        }

        public Criteria andSixBetween(String value1, String value2) {
            addCriterion("six between", value1, value2, "six");
            return (Criteria) this;
        }

        public Criteria andSixNotBetween(String value1, String value2) {
            addCriterion("six not between", value1, value2, "six");
            return (Criteria) this;
        }

        public Criteria andSevenIsNull() {
            addCriterion("seven is null");
            return (Criteria) this;
        }

        public Criteria andSevenIsNotNull() {
            addCriterion("seven is not null");
            return (Criteria) this;
        }

        public Criteria andSevenEqualTo(String value) {
            addCriterion("seven =", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotEqualTo(String value) {
            addCriterion("seven <>", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenGreaterThan(String value) {
            addCriterion("seven >", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenGreaterThanOrEqualTo(String value) {
            addCriterion("seven >=", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenLessThan(String value) {
            addCriterion("seven <", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenLessThanOrEqualTo(String value) {
            addCriterion("seven <=", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenLike(String value) {
            addCriterion("seven like", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotLike(String value) {
            addCriterion("seven not like", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenIn(List<String> values) {
            addCriterion("seven in", values, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotIn(List<String> values) {
            addCriterion("seven not in", values, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenBetween(String value1, String value2) {
            addCriterion("seven between", value1, value2, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotBetween(String value1, String value2) {
            addCriterion("seven not between", value1, value2, "seven");
            return (Criteria) this;
        }

        public Criteria andEightIsNull() {
            addCriterion("eight is null");
            return (Criteria) this;
        }

        public Criteria andEightIsNotNull() {
            addCriterion("eight is not null");
            return (Criteria) this;
        }

        public Criteria andEightEqualTo(String value) {
            addCriterion("eight =", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightNotEqualTo(String value) {
            addCriterion("eight <>", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightGreaterThan(String value) {
            addCriterion("eight >", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightGreaterThanOrEqualTo(String value) {
            addCriterion("eight >=", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightLessThan(String value) {
            addCriterion("eight <", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightLessThanOrEqualTo(String value) {
            addCriterion("eight <=", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightLike(String value) {
            addCriterion("eight like", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightNotLike(String value) {
            addCriterion("eight not like", value, "eight");
            return (Criteria) this;
        }

        public Criteria andEightIn(List<String> values) {
            addCriterion("eight in", values, "eight");
            return (Criteria) this;
        }

        public Criteria andEightNotIn(List<String> values) {
            addCriterion("eight not in", values, "eight");
            return (Criteria) this;
        }

        public Criteria andEightBetween(String value1, String value2) {
            addCriterion("eight between", value1, value2, "eight");
            return (Criteria) this;
        }

        public Criteria andEightNotBetween(String value1, String value2) {
            addCriterion("eight not between", value1, value2, "eight");
            return (Criteria) this;
        }

        public Criteria andNineIsNull() {
            addCriterion("nine is null");
            return (Criteria) this;
        }

        public Criteria andNineIsNotNull() {
            addCriterion("nine is not null");
            return (Criteria) this;
        }

        public Criteria andNineEqualTo(String value) {
            addCriterion("nine =", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineNotEqualTo(String value) {
            addCriterion("nine <>", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineGreaterThan(String value) {
            addCriterion("nine >", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineGreaterThanOrEqualTo(String value) {
            addCriterion("nine >=", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineLessThan(String value) {
            addCriterion("nine <", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineLessThanOrEqualTo(String value) {
            addCriterion("nine <=", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineLike(String value) {
            addCriterion("nine like", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineNotLike(String value) {
            addCriterion("nine not like", value, "nine");
            return (Criteria) this;
        }

        public Criteria andNineIn(List<String> values) {
            addCriterion("nine in", values, "nine");
            return (Criteria) this;
        }

        public Criteria andNineNotIn(List<String> values) {
            addCriterion("nine not in", values, "nine");
            return (Criteria) this;
        }

        public Criteria andNineBetween(String value1, String value2) {
            addCriterion("nine between", value1, value2, "nine");
            return (Criteria) this;
        }

        public Criteria andNineNotBetween(String value1, String value2) {
            addCriterion("nine not between", value1, value2, "nine");
            return (Criteria) this;
        }

        public Criteria andTenIsNull() {
            addCriterion("ten is null");
            return (Criteria) this;
        }

        public Criteria andTenIsNotNull() {
            addCriterion("ten is not null");
            return (Criteria) this;
        }

        public Criteria andTenEqualTo(String value) {
            addCriterion("ten =", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotEqualTo(String value) {
            addCriterion("ten <>", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenGreaterThan(String value) {
            addCriterion("ten >", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenGreaterThanOrEqualTo(String value) {
            addCriterion("ten >=", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenLessThan(String value) {
            addCriterion("ten <", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenLessThanOrEqualTo(String value) {
            addCriterion("ten <=", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenLike(String value) {
            addCriterion("ten like", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotLike(String value) {
            addCriterion("ten not like", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenIn(List<String> values) {
            addCriterion("ten in", values, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotIn(List<String> values) {
            addCriterion("ten not in", values, "ten");
            return (Criteria) this;
        }

        public Criteria andTenBetween(String value1, String value2) {
            addCriterion("ten between", value1, value2, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotBetween(String value1, String value2) {
            addCriterion("ten not between", value1, value2, "ten");
            return (Criteria) this;
        }

        public Criteria andElevenIsNull() {
            addCriterion("eleven is null");
            return (Criteria) this;
        }

        public Criteria andElevenIsNotNull() {
            addCriterion("eleven is not null");
            return (Criteria) this;
        }

        public Criteria andElevenEqualTo(String value) {
            addCriterion("eleven =", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenNotEqualTo(String value) {
            addCriterion("eleven <>", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenGreaterThan(String value) {
            addCriterion("eleven >", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenGreaterThanOrEqualTo(String value) {
            addCriterion("eleven >=", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenLessThan(String value) {
            addCriterion("eleven <", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenLessThanOrEqualTo(String value) {
            addCriterion("eleven <=", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenLike(String value) {
            addCriterion("eleven like", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenNotLike(String value) {
            addCriterion("eleven not like", value, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenIn(List<String> values) {
            addCriterion("eleven in", values, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenNotIn(List<String> values) {
            addCriterion("eleven not in", values, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenBetween(String value1, String value2) {
            addCriterion("eleven between", value1, value2, "eleven");
            return (Criteria) this;
        }

        public Criteria andElevenNotBetween(String value1, String value2) {
            addCriterion("eleven not between", value1, value2, "eleven");
            return (Criteria) this;
        }

        public Criteria andTwelveIsNull() {
            addCriterion("twelve is null");
            return (Criteria) this;
        }

        public Criteria andTwelveIsNotNull() {
            addCriterion("twelve is not null");
            return (Criteria) this;
        }

        public Criteria andTwelveEqualTo(String value) {
            addCriterion("twelve =", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveNotEqualTo(String value) {
            addCriterion("twelve <>", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveGreaterThan(String value) {
            addCriterion("twelve >", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveGreaterThanOrEqualTo(String value) {
            addCriterion("twelve >=", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveLessThan(String value) {
            addCriterion("twelve <", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveLessThanOrEqualTo(String value) {
            addCriterion("twelve <=", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveLike(String value) {
            addCriterion("twelve like", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveNotLike(String value) {
            addCriterion("twelve not like", value, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveIn(List<String> values) {
            addCriterion("twelve in", values, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveNotIn(List<String> values) {
            addCriterion("twelve not in", values, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveBetween(String value1, String value2) {
            addCriterion("twelve between", value1, value2, "twelve");
            return (Criteria) this;
        }

        public Criteria andTwelveNotBetween(String value1, String value2) {
            addCriterion("twelve not between", value1, value2, "twelve");
            return (Criteria) this;
        }

        public Criteria andThirteenIsNull() {
            addCriterion("thirteen is null");
            return (Criteria) this;
        }

        public Criteria andThirteenIsNotNull() {
            addCriterion("thirteen is not null");
            return (Criteria) this;
        }

        public Criteria andThirteenEqualTo(String value) {
            addCriterion("thirteen =", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenNotEqualTo(String value) {
            addCriterion("thirteen <>", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenGreaterThan(String value) {
            addCriterion("thirteen >", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenGreaterThanOrEqualTo(String value) {
            addCriterion("thirteen >=", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenLessThan(String value) {
            addCriterion("thirteen <", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenLessThanOrEqualTo(String value) {
            addCriterion("thirteen <=", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenLike(String value) {
            addCriterion("thirteen like", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenNotLike(String value) {
            addCriterion("thirteen not like", value, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenIn(List<String> values) {
            addCriterion("thirteen in", values, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenNotIn(List<String> values) {
            addCriterion("thirteen not in", values, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenBetween(String value1, String value2) {
            addCriterion("thirteen between", value1, value2, "thirteen");
            return (Criteria) this;
        }

        public Criteria andThirteenNotBetween(String value1, String value2) {
            addCriterion("thirteen not between", value1, value2, "thirteen");
            return (Criteria) this;
        }

        public Criteria andFourteenIsNull() {
            addCriterion("fourteen is null");
            return (Criteria) this;
        }

        public Criteria andFourteenIsNotNull() {
            addCriterion("fourteen is not null");
            return (Criteria) this;
        }

        public Criteria andFourteenEqualTo(String value) {
            addCriterion("fourteen =", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenNotEqualTo(String value) {
            addCriterion("fourteen <>", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenGreaterThan(String value) {
            addCriterion("fourteen >", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenGreaterThanOrEqualTo(String value) {
            addCriterion("fourteen >=", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenLessThan(String value) {
            addCriterion("fourteen <", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenLessThanOrEqualTo(String value) {
            addCriterion("fourteen <=", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenLike(String value) {
            addCriterion("fourteen like", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenNotLike(String value) {
            addCriterion("fourteen not like", value, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenIn(List<String> values) {
            addCriterion("fourteen in", values, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenNotIn(List<String> values) {
            addCriterion("fourteen not in", values, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenBetween(String value1, String value2) {
            addCriterion("fourteen between", value1, value2, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFourteenNotBetween(String value1, String value2) {
            addCriterion("fourteen not between", value1, value2, "fourteen");
            return (Criteria) this;
        }

        public Criteria andFifteenIsNull() {
            addCriterion("fifteen is null");
            return (Criteria) this;
        }

        public Criteria andFifteenIsNotNull() {
            addCriterion("fifteen is not null");
            return (Criteria) this;
        }

        public Criteria andFifteenEqualTo(String value) {
            addCriterion("fifteen =", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenNotEqualTo(String value) {
            addCriterion("fifteen <>", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenGreaterThan(String value) {
            addCriterion("fifteen >", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenGreaterThanOrEqualTo(String value) {
            addCriterion("fifteen >=", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenLessThan(String value) {
            addCriterion("fifteen <", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenLessThanOrEqualTo(String value) {
            addCriterion("fifteen <=", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenLike(String value) {
            addCriterion("fifteen like", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenNotLike(String value) {
            addCriterion("fifteen not like", value, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenIn(List<String> values) {
            addCriterion("fifteen in", values, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenNotIn(List<String> values) {
            addCriterion("fifteen not in", values, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenBetween(String value1, String value2) {
            addCriterion("fifteen between", value1, value2, "fifteen");
            return (Criteria) this;
        }

        public Criteria andFifteenNotBetween(String value1, String value2) {
            addCriterion("fifteen not between", value1, value2, "fifteen");
            return (Criteria) this;
        }

        public Criteria andSixteenIsNull() {
            addCriterion("sixteen is null");
            return (Criteria) this;
        }

        public Criteria andSixteenIsNotNull() {
            addCriterion("sixteen is not null");
            return (Criteria) this;
        }

        public Criteria andSixteenEqualTo(String value) {
            addCriterion("sixteen =", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenNotEqualTo(String value) {
            addCriterion("sixteen <>", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenGreaterThan(String value) {
            addCriterion("sixteen >", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenGreaterThanOrEqualTo(String value) {
            addCriterion("sixteen >=", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenLessThan(String value) {
            addCriterion("sixteen <", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenLessThanOrEqualTo(String value) {
            addCriterion("sixteen <=", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenLike(String value) {
            addCriterion("sixteen like", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenNotLike(String value) {
            addCriterion("sixteen not like", value, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenIn(List<String> values) {
            addCriterion("sixteen in", values, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenNotIn(List<String> values) {
            addCriterion("sixteen not in", values, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenBetween(String value1, String value2) {
            addCriterion("sixteen between", value1, value2, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSixteenNotBetween(String value1, String value2) {
            addCriterion("sixteen not between", value1, value2, "sixteen");
            return (Criteria) this;
        }

        public Criteria andSeventeenIsNull() {
            addCriterion("seventeen is null");
            return (Criteria) this;
        }

        public Criteria andSeventeenIsNotNull() {
            addCriterion("seventeen is not null");
            return (Criteria) this;
        }

        public Criteria andSeventeenEqualTo(String value) {
            addCriterion("seventeen =", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenNotEqualTo(String value) {
            addCriterion("seventeen <>", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenGreaterThan(String value) {
            addCriterion("seventeen >", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenGreaterThanOrEqualTo(String value) {
            addCriterion("seventeen >=", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenLessThan(String value) {
            addCriterion("seventeen <", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenLessThanOrEqualTo(String value) {
            addCriterion("seventeen <=", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenLike(String value) {
            addCriterion("seventeen like", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenNotLike(String value) {
            addCriterion("seventeen not like", value, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenIn(List<String> values) {
            addCriterion("seventeen in", values, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenNotIn(List<String> values) {
            addCriterion("seventeen not in", values, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenBetween(String value1, String value2) {
            addCriterion("seventeen between", value1, value2, "seventeen");
            return (Criteria) this;
        }

        public Criteria andSeventeenNotBetween(String value1, String value2) {
            addCriterion("seventeen not between", value1, value2, "seventeen");
            return (Criteria) this;
        }

        public Criteria andEighteenIsNull() {
            addCriterion("eighteen is null");
            return (Criteria) this;
        }

        public Criteria andEighteenIsNotNull() {
            addCriterion("eighteen is not null");
            return (Criteria) this;
        }

        public Criteria andEighteenEqualTo(String value) {
            addCriterion("eighteen =", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenNotEqualTo(String value) {
            addCriterion("eighteen <>", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenGreaterThan(String value) {
            addCriterion("eighteen >", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenGreaterThanOrEqualTo(String value) {
            addCriterion("eighteen >=", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenLessThan(String value) {
            addCriterion("eighteen <", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenLessThanOrEqualTo(String value) {
            addCriterion("eighteen <=", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenLike(String value) {
            addCriterion("eighteen like", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenNotLike(String value) {
            addCriterion("eighteen not like", value, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenIn(List<String> values) {
            addCriterion("eighteen in", values, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenNotIn(List<String> values) {
            addCriterion("eighteen not in", values, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenBetween(String value1, String value2) {
            addCriterion("eighteen between", value1, value2, "eighteen");
            return (Criteria) this;
        }

        public Criteria andEighteenNotBetween(String value1, String value2) {
            addCriterion("eighteen not between", value1, value2, "eighteen");
            return (Criteria) this;
        }

        public Criteria andNineteenIsNull() {
            addCriterion("nineteen is null");
            return (Criteria) this;
        }

        public Criteria andNineteenIsNotNull() {
            addCriterion("nineteen is not null");
            return (Criteria) this;
        }

        public Criteria andNineteenEqualTo(String value) {
            addCriterion("nineteen =", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenNotEqualTo(String value) {
            addCriterion("nineteen <>", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenGreaterThan(String value) {
            addCriterion("nineteen >", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenGreaterThanOrEqualTo(String value) {
            addCriterion("nineteen >=", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenLessThan(String value) {
            addCriterion("nineteen <", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenLessThanOrEqualTo(String value) {
            addCriterion("nineteen <=", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenLike(String value) {
            addCriterion("nineteen like", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenNotLike(String value) {
            addCriterion("nineteen not like", value, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenIn(List<String> values) {
            addCriterion("nineteen in", values, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenNotIn(List<String> values) {
            addCriterion("nineteen not in", values, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenBetween(String value1, String value2) {
            addCriterion("nineteen between", value1, value2, "nineteen");
            return (Criteria) this;
        }

        public Criteria andNineteenNotBetween(String value1, String value2) {
            addCriterion("nineteen not between", value1, value2, "nineteen");
            return (Criteria) this;
        }

        public Criteria andTwentyIsNull() {
            addCriterion("twenty is null");
            return (Criteria) this;
        }

        public Criteria andTwentyIsNotNull() {
            addCriterion("twenty is not null");
            return (Criteria) this;
        }

        public Criteria andTwentyEqualTo(String value) {
            addCriterion("twenty =", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyNotEqualTo(String value) {
            addCriterion("twenty <>", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyGreaterThan(String value) {
            addCriterion("twenty >", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyGreaterThanOrEqualTo(String value) {
            addCriterion("twenty >=", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyLessThan(String value) {
            addCriterion("twenty <", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyLessThanOrEqualTo(String value) {
            addCriterion("twenty <=", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyLike(String value) {
            addCriterion("twenty like", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyNotLike(String value) {
            addCriterion("twenty not like", value, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyIn(List<String> values) {
            addCriterion("twenty in", values, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyNotIn(List<String> values) {
            addCriterion("twenty not in", values, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyBetween(String value1, String value2) {
            addCriterion("twenty between", value1, value2, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyNotBetween(String value1, String value2) {
            addCriterion("twenty not between", value1, value2, "twenty");
            return (Criteria) this;
        }

        public Criteria andTwentyOneIsNull() {
            addCriterion("twenty_one is null");
            return (Criteria) this;
        }

        public Criteria andTwentyOneIsNotNull() {
            addCriterion("twenty_one is not null");
            return (Criteria) this;
        }

        public Criteria andTwentyOneEqualTo(String value) {
            addCriterion("twenty_one =", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneNotEqualTo(String value) {
            addCriterion("twenty_one <>", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneGreaterThan(String value) {
            addCriterion("twenty_one >", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneGreaterThanOrEqualTo(String value) {
            addCriterion("twenty_one >=", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneLessThan(String value) {
            addCriterion("twenty_one <", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneLessThanOrEqualTo(String value) {
            addCriterion("twenty_one <=", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneLike(String value) {
            addCriterion("twenty_one like", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneNotLike(String value) {
            addCriterion("twenty_one not like", value, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneIn(List<String> values) {
            addCriterion("twenty_one in", values, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneNotIn(List<String> values) {
            addCriterion("twenty_one not in", values, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneBetween(String value1, String value2) {
            addCriterion("twenty_one between", value1, value2, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyOneNotBetween(String value1, String value2) {
            addCriterion("twenty_one not between", value1, value2, "twentyOne");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoIsNull() {
            addCriterion("twenty_two is null");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoIsNotNull() {
            addCriterion("twenty_two is not null");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoEqualTo(String value) {
            addCriterion("twenty_two =", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoNotEqualTo(String value) {
            addCriterion("twenty_two <>", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoGreaterThan(String value) {
            addCriterion("twenty_two >", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoGreaterThanOrEqualTo(String value) {
            addCriterion("twenty_two >=", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoLessThan(String value) {
            addCriterion("twenty_two <", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoLessThanOrEqualTo(String value) {
            addCriterion("twenty_two <=", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoLike(String value) {
            addCriterion("twenty_two like", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoNotLike(String value) {
            addCriterion("twenty_two not like", value, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoIn(List<String> values) {
            addCriterion("twenty_two in", values, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoNotIn(List<String> values) {
            addCriterion("twenty_two not in", values, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoBetween(String value1, String value2) {
            addCriterion("twenty_two between", value1, value2, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyTwoNotBetween(String value1, String value2) {
            addCriterion("twenty_two not between", value1, value2, "twentyTwo");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeIsNull() {
            addCriterion("twenty_three is null");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeIsNotNull() {
            addCriterion("twenty_three is not null");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeEqualTo(String value) {
            addCriterion("twenty_three =", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeNotEqualTo(String value) {
            addCriterion("twenty_three <>", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeGreaterThan(String value) {
            addCriterion("twenty_three >", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeGreaterThanOrEqualTo(String value) {
            addCriterion("twenty_three >=", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeLessThan(String value) {
            addCriterion("twenty_three <", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeLessThanOrEqualTo(String value) {
            addCriterion("twenty_three <=", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeLike(String value) {
            addCriterion("twenty_three like", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeNotLike(String value) {
            addCriterion("twenty_three not like", value, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeIn(List<String> values) {
            addCriterion("twenty_three in", values, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeNotIn(List<String> values) {
            addCriterion("twenty_three not in", values, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeBetween(String value1, String value2) {
            addCriterion("twenty_three between", value1, value2, "twentyThree");
            return (Criteria) this;
        }

        public Criteria andTwentyThreeNotBetween(String value1, String value2) {
            addCriterion("twenty_three not between", value1, value2, "twentyThree");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table sms_employee_schedule
     * @mbggenerated  Thu Jul 21 22:04:00 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_employee_schedule
     *
     * @mbggenerated do_not_delete_during_merge Wed May 04 17:06:17 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}