package com.dzmsoft.sms.base.pojo;

public class SmsHouseholdRequire {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_household_require.id
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_household_require.requirement
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    private String requirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_household_require.order_id
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_household_require.id
     *
     * @return the value of sms_household_require.id
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_household_require.id
     *
     * @param id the value for sms_household_require.id
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_household_require.requirement
     *
     * @return the value of sms_household_require.requirement
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_household_require.requirement
     *
     * @param requirement the value for sms_household_require.requirement
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_household_require.order_id
     *
     * @return the value of sms_household_require.order_id
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_household_require.order_id
     *
     * @param orderId the value for sms_household_require.order_id
     *
     * @mbggenerated Thu Jun 09 14:52:07 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}